# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KeyBoardForm.ui'
#
# Created: Fri Mar  8 16:34:02 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(566, 323)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("")
        self.gridLayout_8 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.HouXuan1_2 = QtWidgets.QLabel(Dialog)
        self.HouXuan1_2.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HouXuan1_2.setFont(font)
        self.HouXuan1_2.setStyleSheet("")
        self.HouXuan1_2.setText("")
        self.HouXuan1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HouXuan1_2.setObjectName("HouXuan1_2")
        self.gridLayout_4.addWidget(self.HouXuan1_2, 0, 2, 1, 1)
        self.HouXuan1_7 = QtWidgets.QLabel(Dialog)
        self.HouXuan1_7.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HouXuan1_7.setFont(font)
        self.HouXuan1_7.setStyleSheet("")
        self.HouXuan1_7.setText("")
        self.HouXuan1_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HouXuan1_7.setObjectName("HouXuan1_7")
        self.gridLayout_4.addWidget(self.HouXuan1_7, 0, 7, 1, 1)
        self.HouXuan1_5 = QtWidgets.QLabel(Dialog)
        self.HouXuan1_5.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HouXuan1_5.setFont(font)
        self.HouXuan1_5.setStyleSheet("")
        self.HouXuan1_5.setText("")
        self.HouXuan1_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HouXuan1_5.setObjectName("HouXuan1_5")
        self.gridLayout_4.addWidget(self.HouXuan1_5, 0, 5, 1, 1)
        self.HouXuan1_6 = QtWidgets.QLabel(Dialog)
        self.HouXuan1_6.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HouXuan1_6.setFont(font)
        self.HouXuan1_6.setStyleSheet("")
        self.HouXuan1_6.setText("")
        self.HouXuan1_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HouXuan1_6.setObjectName("HouXuan1_6")
        self.gridLayout_4.addWidget(self.HouXuan1_6, 0, 6, 1, 1)
        self.nextone = QtWidgets.QLabel(Dialog)
        self.nextone.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.nextone.setFont(font)
        self.nextone.setStyleSheet("")
        self.nextone.setText("")
        self.nextone.setAlignment(QtCore.Qt.AlignCenter)
        self.nextone.setObjectName("nextone")
        self.gridLayout_4.addWidget(self.nextone, 0, 9, 1, 1)
        self.HouXuan1_4 = QtWidgets.QLabel(Dialog)
        self.HouXuan1_4.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HouXuan1_4.setFont(font)
        self.HouXuan1_4.setStyleSheet("")
        self.HouXuan1_4.setText("")
        self.HouXuan1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HouXuan1_4.setObjectName("HouXuan1_4")
        self.gridLayout_4.addWidget(self.HouXuan1_4, 0, 4, 1, 1)
        self.HouXuan1_3 = QtWidgets.QLabel(Dialog)
        self.HouXuan1_3.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HouXuan1_3.setFont(font)
        self.HouXuan1_3.setStyleSheet("")
        self.HouXuan1_3.setText("")
        self.HouXuan1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HouXuan1_3.setObjectName("HouXuan1_3")
        self.gridLayout_4.addWidget(self.HouXuan1_3, 0, 3, 1, 1)
        self.HouXuan1_8 = QtWidgets.QLabel(Dialog)
        self.HouXuan1_8.setMinimumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.HouXuan1_8.setFont(font)
        self.HouXuan1_8.setStyleSheet("")
        self.HouXuan1_8.setText("")
        self.HouXuan1_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HouXuan1_8.setObjectName("HouXuan1_8")
        self.gridLayout_4.addWidget(self.HouXuan1_8, 0, 8, 1, 1)
        self.beforeone = QtWidgets.QLabel(Dialog)
        self.beforeone.setMinimumSize(QtCore.QSize(25, 25))
        self.beforeone.setStyleSheet("")
        self.beforeone.setText("")
        self.beforeone.setAlignment(QtCore.Qt.AlignCenter)
        self.beforeone.setObjectName("beforeone")
        self.gridLayout_4.addWidget(self.beforeone, 0, 0, 1, 1)
        self.PU_pinyin = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PU_pinyin.sizePolicy().hasHeightForWidth())
        self.PU_pinyin.setSizePolicy(sizePolicy)
        self.PU_pinyin.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PU_pinyin.setFont(font)
        self.PU_pinyin.setObjectName("PU_pinyin")
        self.gridLayout_4.addWidget(self.PU_pinyin, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 0, 0, 1, 3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.K_DEL = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_DEL.sizePolicy().hasHeightForWidth())
        self.K_DEL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.K_DEL.setFont(font)
        self.K_DEL.setObjectName("K_DEL")
        self.gridLayout_3.addWidget(self.K_DEL, 0, 1, 1, 1)
        self.K_OK = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_OK.sizePolicy().hasHeightForWidth())
        self.K_OK.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.K_OK.setFont(font)
        self.K_OK.setObjectName("K_OK")
        self.gridLayout_3.addWidget(self.K_OK, 0, 2, 1, 1)
        self.K_SHOW = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_SHOW.sizePolicy().hasHeightForWidth())
        self.K_SHOW.setSizePolicy(sizePolicy)
        self.K_SHOW.setMinimumSize(QtCore.QSize(7, 0))
        self.K_SHOW.setObjectName("K_SHOW")
        self.gridLayout_3.addWidget(self.K_SHOW, 0, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 1, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.K_9 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_9.sizePolicy().hasHeightForWidth())
        self.K_9.setSizePolicy(sizePolicy)
        self.K_9.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_9.setFont(font)
        self.K_9.setObjectName("K_9")
        self.gridLayout_2.addWidget(self.K_9, 0, 9, 1, 1)
        self.K_7 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_7.sizePolicy().hasHeightForWidth())
        self.K_7.setSizePolicy(sizePolicy)
        self.K_7.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_7.setFont(font)
        self.K_7.setObjectName("K_7")
        self.gridLayout_2.addWidget(self.K_7, 0, 7, 1, 1)
        self.K_6 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_6.sizePolicy().hasHeightForWidth())
        self.K_6.setSizePolicy(sizePolicy)
        self.K_6.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_6.setFont(font)
        self.K_6.setObjectName("K_6")
        self.gridLayout_2.addWidget(self.K_6, 0, 6, 1, 1)
        self.K_3 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_3.sizePolicy().hasHeightForWidth())
        self.K_3.setSizePolicy(sizePolicy)
        self.K_3.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_3.setFont(font)
        self.K_3.setObjectName("K_3")
        self.gridLayout_2.addWidget(self.K_3, 0, 3, 1, 1)
        self.K_5 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_5.sizePolicy().hasHeightForWidth())
        self.K_5.setSizePolicy(sizePolicy)
        self.K_5.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_5.setFont(font)
        self.K_5.setObjectName("K_5")
        self.gridLayout_2.addWidget(self.K_5, 0, 5, 1, 1)
        self.K_8 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_8.sizePolicy().hasHeightForWidth())
        self.K_8.setSizePolicy(sizePolicy)
        self.K_8.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_8.setFont(font)
        self.K_8.setObjectName("K_8")
        self.gridLayout_2.addWidget(self.K_8, 0, 8, 1, 1)
        self.K_1 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_1.sizePolicy().hasHeightForWidth())
        self.K_1.setSizePolicy(sizePolicy)
        self.K_1.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_1.setFont(font)
        self.K_1.setObjectName("K_1")
        self.gridLayout_2.addWidget(self.K_1, 0, 1, 1, 1)
        self.K_DOT = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_DOT.sizePolicy().hasHeightForWidth())
        self.K_DOT.setSizePolicy(sizePolicy)
        self.K_DOT.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.K_DOT.setFont(font)
        self.K_DOT.setObjectName("K_DOT")
        self.gridLayout_2.addWidget(self.K_DOT, 0, 11, 1, 1)
        self.K_4 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_4.sizePolicy().hasHeightForWidth())
        self.K_4.setSizePolicy(sizePolicy)
        self.K_4.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_4.setFont(font)
        self.K_4.setObjectName("K_4")
        self.gridLayout_2.addWidget(self.K_4, 0, 4, 1, 1)
        self.K_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_2.sizePolicy().hasHeightForWidth())
        self.K_2.setSizePolicy(sizePolicy)
        self.K_2.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_2.setFont(font)
        self.K_2.setObjectName("K_2")
        self.gridLayout_2.addWidget(self.K_2, 0, 2, 1, 1)
        self.K_0 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_0.sizePolicy().hasHeightForWidth())
        self.K_0.setSizePolicy(sizePolicy)
        self.K_0.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_0.setFont(font)
        self.K_0.setObjectName("K_0")
        self.gridLayout_2.addWidget(self.K_0, 0, 0, 1, 1)
        self.K_MINUS = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_MINUS.sizePolicy().hasHeightForWidth())
        self.K_MINUS.setSizePolicy(sizePolicy)
        self.K_MINUS.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.K_MINUS.setFont(font)
        self.K_MINUS.setObjectName("K_MINUS")
        self.gridLayout_2.addWidget(self.K_MINUS, 0, 12, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_2, 2, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.K_Q = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_Q.sizePolicy().hasHeightForWidth())
        self.K_Q.setSizePolicy(sizePolicy)
        self.K_Q.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_Q.setFont(font)
        self.K_Q.setObjectName("K_Q")
        self.gridLayout.addWidget(self.K_Q, 0, 0, 1, 1)
        self.K_W = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_W.sizePolicy().hasHeightForWidth())
        self.K_W.setSizePolicy(sizePolicy)
        self.K_W.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_W.setFont(font)
        self.K_W.setObjectName("K_W")
        self.gridLayout.addWidget(self.K_W, 0, 1, 1, 1)
        self.K_E = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_E.sizePolicy().hasHeightForWidth())
        self.K_E.setSizePolicy(sizePolicy)
        self.K_E.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_E.setFont(font)
        self.K_E.setObjectName("K_E")
        self.gridLayout.addWidget(self.K_E, 0, 2, 1, 1)
        self.K_R = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_R.sizePolicy().hasHeightForWidth())
        self.K_R.setSizePolicy(sizePolicy)
        self.K_R.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_R.setFont(font)
        self.K_R.setObjectName("K_R")
        self.gridLayout.addWidget(self.K_R, 0, 3, 1, 1)
        self.K_T = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_T.sizePolicy().hasHeightForWidth())
        self.K_T.setSizePolicy(sizePolicy)
        self.K_T.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_T.setFont(font)
        self.K_T.setObjectName("K_T")
        self.gridLayout.addWidget(self.K_T, 0, 4, 1, 1)
        self.K_Y = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_Y.sizePolicy().hasHeightForWidth())
        self.K_Y.setSizePolicy(sizePolicy)
        self.K_Y.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_Y.setFont(font)
        self.K_Y.setObjectName("K_Y")
        self.gridLayout.addWidget(self.K_Y, 0, 5, 1, 1)
        self.K_U = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_U.sizePolicy().hasHeightForWidth())
        self.K_U.setSizePolicy(sizePolicy)
        self.K_U.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_U.setFont(font)
        self.K_U.setObjectName("K_U")
        self.gridLayout.addWidget(self.K_U, 0, 6, 1, 1)
        self.K_I = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_I.sizePolicy().hasHeightForWidth())
        self.K_I.setSizePolicy(sizePolicy)
        self.K_I.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_I.setFont(font)
        self.K_I.setObjectName("K_I")
        self.gridLayout.addWidget(self.K_I, 0, 7, 1, 1)
        self.K_O = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_O.sizePolicy().hasHeightForWidth())
        self.K_O.setSizePolicy(sizePolicy)
        self.K_O.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_O.setFont(font)
        self.K_O.setObjectName("K_O")
        self.gridLayout.addWidget(self.K_O, 0, 8, 1, 1)
        self.K_P = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_P.sizePolicy().hasHeightForWidth())
        self.K_P.setSizePolicy(sizePolicy)
        self.K_P.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_P.setFont(font)
        self.K_P.setObjectName("K_P")
        self.gridLayout.addWidget(self.K_P, 0, 9, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 3, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 3, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 4, 0, 1, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.K_S = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_S.sizePolicy().hasHeightForWidth())
        self.K_S.setSizePolicy(sizePolicy)
        self.K_S.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_S.setFont(font)
        self.K_S.setObjectName("K_S")
        self.gridLayout_5.addWidget(self.K_S, 0, 1, 1, 1)
        self.K_A = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_A.sizePolicy().hasHeightForWidth())
        self.K_A.setSizePolicy(sizePolicy)
        self.K_A.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_A.setFont(font)
        self.K_A.setObjectName("K_A")
        self.gridLayout_5.addWidget(self.K_A, 0, 0, 1, 1)
        self.K_F = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_F.sizePolicy().hasHeightForWidth())
        self.K_F.setSizePolicy(sizePolicy)
        self.K_F.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_F.setFont(font)
        self.K_F.setObjectName("K_F")
        self.gridLayout_5.addWidget(self.K_F, 0, 3, 1, 1)
        self.K_H = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_H.sizePolicy().hasHeightForWidth())
        self.K_H.setSizePolicy(sizePolicy)
        self.K_H.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_H.setFont(font)
        self.K_H.setObjectName("K_H")
        self.gridLayout_5.addWidget(self.K_H, 0, 5, 1, 1)
        self.K_D = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_D.sizePolicy().hasHeightForWidth())
        self.K_D.setSizePolicy(sizePolicy)
        self.K_D.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_D.setFont(font)
        self.K_D.setObjectName("K_D")
        self.gridLayout_5.addWidget(self.K_D, 0, 2, 1, 1)
        self.K_L = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_L.sizePolicy().hasHeightForWidth())
        self.K_L.setSizePolicy(sizePolicy)
        self.K_L.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_L.setFont(font)
        self.K_L.setObjectName("K_L")
        self.gridLayout_5.addWidget(self.K_L, 0, 8, 1, 1)
        self.K_K = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_K.sizePolicy().hasHeightForWidth())
        self.K_K.setSizePolicy(sizePolicy)
        self.K_K.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_K.setFont(font)
        self.K_K.setObjectName("K_K")
        self.gridLayout_5.addWidget(self.K_K, 0, 7, 1, 1)
        self.K_J = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_J.sizePolicy().hasHeightForWidth())
        self.K_J.setSizePolicy(sizePolicy)
        self.K_J.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_J.setFont(font)
        self.K_J.setObjectName("K_J")
        self.gridLayout_5.addWidget(self.K_J, 0, 6, 1, 1)
        self.K_G = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_G.sizePolicy().hasHeightForWidth())
        self.K_G.setSizePolicy(sizePolicy)
        self.K_G.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_G.setFont(font)
        self.K_G.setObjectName("K_G")
        self.gridLayout_5.addWidget(self.K_G, 0, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 4, 3, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 5, 0, 1, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.K_Shift = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_Shift.sizePolicy().hasHeightForWidth())
        self.K_Shift.setSizePolicy(sizePolicy)
        self.K_Shift.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.K_Shift.setFont(font)
        self.K_Shift.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.K_Shift.setObjectName("K_Shift")
        self.gridLayout_7.addWidget(self.K_Shift, 0, 0, 1, 1)
        self.PU_Chinese = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PU_Chinese.sizePolicy().hasHeightForWidth())
        self.PU_Chinese.setSizePolicy(sizePolicy)
        self.PU_Chinese.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PU_Chinese.setFont(font)
        self.PU_Chinese.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.PU_Chinese.setObjectName("PU_Chinese")
        self.gridLayout_7.addWidget(self.PU_Chinese, 0, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.K_Z = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_Z.sizePolicy().hasHeightForWidth())
        self.K_Z.setSizePolicy(sizePolicy)
        self.K_Z.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_Z.setFont(font)
        self.K_Z.setObjectName("K_Z")
        self.gridLayout_6.addWidget(self.K_Z, 0, 0, 1, 1)
        self.K_X = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_X.sizePolicy().hasHeightForWidth())
        self.K_X.setSizePolicy(sizePolicy)
        self.K_X.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_X.setFont(font)
        self.K_X.setObjectName("K_X")
        self.gridLayout_6.addWidget(self.K_X, 0, 1, 1, 1)
        self.K_C = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_C.sizePolicy().hasHeightForWidth())
        self.K_C.setSizePolicy(sizePolicy)
        self.K_C.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_C.setFont(font)
        self.K_C.setObjectName("K_C")
        self.gridLayout_6.addWidget(self.K_C, 0, 2, 1, 1)
        self.K_V = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_V.sizePolicy().hasHeightForWidth())
        self.K_V.setSizePolicy(sizePolicy)
        self.K_V.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_V.setFont(font)
        self.K_V.setObjectName("K_V")
        self.gridLayout_6.addWidget(self.K_V, 0, 3, 1, 1)
        self.K_B = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_B.sizePolicy().hasHeightForWidth())
        self.K_B.setSizePolicy(sizePolicy)
        self.K_B.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_B.setFont(font)
        self.K_B.setObjectName("K_B")
        self.gridLayout_6.addWidget(self.K_B, 0, 4, 1, 1)
        self.K_N = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_N.sizePolicy().hasHeightForWidth())
        self.K_N.setSizePolicy(sizePolicy)
        self.K_N.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_N.setFont(font)
        self.K_N.setObjectName("K_N")
        self.gridLayout_6.addWidget(self.K_N, 0, 5, 1, 1)
        self.K_M = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.K_M.sizePolicy().hasHeightForWidth())
        self.K_M.setSizePolicy(sizePolicy)
        self.K_M.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.K_M.setFont(font)
        self.K_M.setObjectName("K_M")
        self.gridLayout_6.addWidget(self.K_M, 0, 6, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 5, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 5, 3, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.K_DEL.setText(_translate("Dialog", "DEL"))
        self.K_OK.setText(_translate("Dialog", "OK"))
        self.K_9.setText(_translate("Dialog", "9"))
        self.K_7.setText(_translate("Dialog", "7"))
        self.K_6.setText(_translate("Dialog", "6"))
        self.K_3.setText(_translate("Dialog", "3"))
        self.K_5.setText(_translate("Dialog", "5"))
        self.K_8.setText(_translate("Dialog", "8"))
        self.K_1.setText(_translate("Dialog", "1"))
        self.K_DOT.setText(_translate("Dialog", "."))
        self.K_4.setText(_translate("Dialog", "4"))
        self.K_2.setText(_translate("Dialog", "2"))
        self.K_0.setText(_translate("Dialog", "0"))
        self.K_MINUS.setText(_translate("Dialog", "-"))
        self.K_Q.setText(_translate("Dialog", "Q"))
        self.K_W.setText(_translate("Dialog", "W"))
        self.K_E.setText(_translate("Dialog", "E"))
        self.K_R.setText(_translate("Dialog", "R"))
        self.K_T.setText(_translate("Dialog", "T"))
        self.K_Y.setText(_translate("Dialog", "Y"))
        self.K_U.setText(_translate("Dialog", "U"))
        self.K_I.setText(_translate("Dialog", "I"))
        self.K_O.setText(_translate("Dialog", "O"))
        self.K_P.setText(_translate("Dialog", "P"))
        self.K_S.setText(_translate("Dialog", "S"))
        self.K_A.setText(_translate("Dialog", "A"))
        self.K_F.setText(_translate("Dialog", "F"))
        self.K_H.setText(_translate("Dialog", "H"))
        self.K_D.setText(_translate("Dialog", "D"))
        self.K_L.setText(_translate("Dialog", "L"))
        self.K_K.setText(_translate("Dialog", "K"))
        self.K_J.setText(_translate("Dialog", "J"))
        self.K_G.setText(_translate("Dialog", "G"))
        self.K_Shift.setText(_translate("Dialog", "Shift"))
        self.PU_Chinese.setText(_translate("Dialog", "中"))
        self.K_Z.setText(_translate("Dialog", "Z"))
        self.K_X.setText(_translate("Dialog", "X"))
        self.K_C.setText(_translate("Dialog", "C"))
        self.K_V.setText(_translate("Dialog", "V"))
        self.K_B.setText(_translate("Dialog", "B"))
        self.K_N.setText(_translate("Dialog", "N"))
        self.K_M.setText(_translate("Dialog", "M"))

